version: '3.4'
services:

  leprikon:
    image: leprikon/leprikon
    depends_on:
      - memcached
      - mysql
      - smtp
    environment:
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: ddmlanskroun
      DATABASE_PASSWORD: dbpassword
      DATABASE_USER: ddmlanskroun
      EMAIL_HOST: smtp
      EMAIL_HOST_PASSWORD: emailpassword
      EMAIL_HOST_USER: ddmlanskroun
      EMAIL_SUBJECT_PREFIX: '[DDM Lanškroun]'
      MEMCACHED_LOCATION: memcached:11211
      SECRET_KEY: secretkey
      SERVER_EMAIL: '"DDM Lanškroun" <leprikon@ddmlanskroun.leprikon.cz>'
      SUPERVISORD_RUN: nginx uwsgi
    ports:
      - 127.0.0.1:10090:80
    volumes:
      - ./.ipython:/root/.ipython
      - ./data:/app/data
      - ./media:/app/htdocs/media
      - mysql:/var/run/mysqld

  memcached:
    image: memcached

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: ddmlanskroun
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootdbpassword
      MYSQL_USER: ddmlanskroun
    volumes:
      - mysql:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  smtp:
    image: catatnight/postfix
    environment:
      maildomain: ddmlanskroun.leprikon.cz
      smtp_user: ddmlanskroun:emailpassword
    stdin_open: true
    volumes:
    - ./dkim:/etc/opendkim/domainkeys
    tty: true

volumes:
  mysql:
